"""Step 173 — WHERE does the degree-4 readout break? Sweep the size of the reducible algebra.

WHY. §172 built the degree-4 positive control in geodesic flow (Cariglia-Galajinsky 5D Ricci-flat metric) and the
readout FAILED to isolate the known rank-4 Killing tensor, with a named mechanism: the degree-4 reducible algebra
there is 45 elements generated by only FOUR quantities (p_t, p_s, p_w, H), hence inherently near-collinear.

THE NUANCE §172 DID NOT TEST, and it matters for P3. **The CG control is HARDER than the actual target.** CG's
metric has THREE Killing vectors; bumped Kerr has TWO (p_t, p_phi). So bumped Kerr's degree-4 reducible algebra
is roughly 21 elements, not 45, and §172's negative may be over-pessimistic for the spacetime the question is
actually about. Reporting "the instrument fails at degree 4 in geodesic flow" without testing this would be
generalising from the hardest case available.

THE KNOB. On the SAME substrate, restrict the ensemble so some Killing momenta vanish identically. They are
conserved, so a zero stays zero, and the corresponding reducibles drop out. Which ones can be zeroed without
destroying the target is a physics question, checked rather than assumed:
    p_s = g_sA u^A = u^t          -> K is built from u^t; zeroing this DESTROYS the target. Never zeroed.
    p_t = -2U u^t + u^s + alpha x u^w   -> constrains u^s, which K does not contain at all. Safe.
    p_w = alpha x u^t + u^w       -> constrains u^w; K retains terms without u^w. Safe but partial.
So the sweep is {p_t, p_s, p_w all free} -> {p_t = 0} -> {p_t = p_w = 0}, shrinking the algebra while keeping a
genuine irreducible rank-4 invariant present throughout.

PRE-REGISTERED, both outcomes are results:
  W0 the target SURVIVES each restriction -- K still conserved and still irreducible against the restricted
     reducible set. A restriction that kills the target is reported and dropped, not screened.
  W1 the reducible rank is MEASURED at each restriction (never counted by hand).
  W2 at each restriction: does the readout isolate K? Same statistic as §172 -- K's residual in the conserved
     span, against a smooth non-conserved control that must score worse.
  W3 THE WALL: report the largest reducible rank at which the readout still finds K, and the smallest at which
     it does not. If it succeeds around rank ~21, §172's negative does NOT transfer to bumped Kerr and §168's
     degree-4 rungs deserve a rerun. If it fails even at the smallest algebra, the negative is robust and
     degree-4 numerical nulls on any spacetime stay REFUSED.

This does not re-litigate §172. Its verdict stands for the CG substrate as recorded; this measures how far that
verdict reaches.
"""

import json
import sys
from importlib import import_module
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

import matplotlib

matplotlib.use("Agg")
import matplotlib.pyplot as plt
import numpy as np
import torch

from curvlib import RESULTS

m172 = import_module("172_degree4_geodesic_control")
s99 = m172.s99
torch.set_default_dtype(torch.float64)
np.seterr(all="ignore")

AL, GA = m172.AL, m172.GA
FAST = "--fast" in sys.argv[1:]
NTRAJ = 150 if FAST else 300
NSTEP = 6000 if FAST else 9000
STRIDE = 40 if FAST else 45


def geodesics(seed, zero, n):
    """Ensemble with the named Killing momenta pinned to zero. They are conserved, so zero stays zero."""
    g = np.random.default_rng(seed)
    z = torch.tensor(np.stack([g.uniform(0, 1, n), g.uniform(0, 1, n), g.uniform(2.0, 3.0, n),
                               g.uniform(-1, 1, n), g.uniform(-1, 1, n)], -1))
    p = torch.tensor(g.uniform(-0.3, 0.3, (n, 5)))
    # p index order is (t, s, x, y, w); pin by solving for the conjugate slot
    if "pw" in zero:
        p[:, 4] = 0.0
    if "pt" in zero:
        p[:, 0] = 0.0
    alive = torch.ones(n, dtype=torch.bool)
    rec = []
    for i in range(NSTEP):
        k1z, k1p = m172.deriv(z, p)
        k2z, k2p = m172.deriv(z + .5 * m172.DT * k1z, p + .5 * m172.DT * k1p)
        k3z, k3p = m172.deriv(z + .5 * m172.DT * k2z, p + .5 * m172.DT * k2p)
        k4z, k4p = m172.deriv(z + m172.DT * k3z, p + m172.DT * k3p)
        z = z + m172.DT / 6 * (k1z + 2 * k2z + 2 * k3z + k4z)
        p = p + m172.DT / 6 * (k1p + 2 * k2p + 2 * k3p + k4p)
        alive = alive & torch.isfinite(z).all(-1) & torch.isfinite(p).all(-1) \
            & (z[:, 2] > m172.X_LO) & (z[:, 2] < m172.X_HI)
        z = torch.where(alive[:, None], z, torch.tensor([0., 0., 1., 0., 0.]))
        p = torch.where(alive[:, None], p, torch.zeros(5))
        if i % STRIDE == 0:
            rec.append(torch.cat([z, p], -1))
    return torch.stack(rec, 1)[alive].numpy()


def reducibles(T, zero):
    """Monomials in the SURVIVING Killing momenta and H, total degree <= 4."""
    P = T[..., 5:]
    gens = []
    if "pt" not in zero:
        gens.append((P[..., 0], "pt"))
    gens.append((P[..., 1], "ps"))
    if "pw" not in zero:
        gens.append((P[..., 4], "pw"))
    H = m172.H_of(T)
    out = []

    def rec(i, acc, d, lab):
        if d > 4:
            return
        if i == len(gens):
            if lab:
                out.append((acc, lab))
            return
        v, nm = gens[i]
        pw_ = np.ones_like(H)
        e = 0
        while d + e <= 4:
            rec(i + 1, acc * pw_, d + e, lab + (f"{nm}^{e}" if e else ""))
            e += 1
            pw_ = pw_ * v
    rec(0, np.ones_like(H), 0, "")
    extra = []
    for v, lab in list(out) + [(np.ones_like(H), "")]:
        extra.append((v * H, lab + "H"))
    out = out + [(a, b) for a, b in extra if b]
    out.append((H * H, "HH"))
    return out


def main():
    out = {"question": "how far does §172's degree-4 negative reach? sweep the reducible-algebra size",
           "substrate": "same CG 5D Ricci-flat metric as §172", "rows": []}
    print("W: sweeping the reducible algebra on the SAME substrate (CG 5D Ricci-flat)")
    print(f"{'restriction':16s} {'G':>4} {'red rank':>9} {'K drift':>10} {'K irred R2':>11} "
          f"{'n_cons':>7} {'K resid':>10} {'ctrl resid':>10} {'finds K':>8}")
    for zero, label in [(set(), "none (3 KVs)"), ({"pt"}, "p_t=0 (2 KVs)"), ({"pt", "pw"}, "p_t=p_w=0 (1 KV)")]:
        Ttr, Tte = geodesics(1, zero, NTRAJ), geodesics(51, zero, NTRAJ)
        if len(Ttr) < 20 or len(Tte) < 20:
            print(f"{label:16s} too few survivors ({len(Ttr)}/{len(Tte)}) -- reported, not screened")
            out["rows"].append({"restriction": label, "skipped": "too few survivors"})
            continue
        # W0 GUARD: the knob is CONFOUNDED and this catches it. Pinning momenta shrinks the algebra, but it also
        # imposes linear constraints on the velocities, which collapses the state space the library sees and can
        # degrade how well K is REPRESENTED. A row where K's representability has moved is not a measurement of
        # algebra size -- it is a different experiment -- and is REFUSED rather than reported.
        Fa_g, _ = m172.library(Ttr)
        Vg = m172.cond_basis(Fa_g)
        Zg = ((Fa_g @ Vg) - (Fa_g @ Vg).reshape(-1, (Fa_g @ Vg).shape[-1]).mean(0))
        Zg = (Fa_g @ Vg).reshape(-1, (Fa_g @ Vg).shape[-1])
        Zg = (Zg - Zg.mean(0)) / (Zg.std(0) + 1e-300)
        Zga = np.concatenate([Zg, np.ones((len(Zg), 1))], 1)
        yg = m172.K_of(Ttr).reshape(-1)
        cg, *_ = np.linalg.lstsq(Zga, yg, rcond=None)
        k_repr = float(np.linalg.norm(Zga @ cg - yg) / (np.linalg.norm(yg - yg.mean()) + 1e-300))
        dK = m172.rel_drift(m172.K_of(Tte))
        red = reducibles(Tte, zero)
        R = np.stack([v.mean(1) for v, _ in red], 1)
        rank_red = m172.gap_rank(R)
        yK = m172.K_of(Tte).mean(1)
        ykf = m172.known_fail(Tte).mean(1)
        r2 = 1 - m172.in_span(R, yK) ** 2
        Fa, _ = m172.library(Ttr)
        Fb, _ = m172.library(Tte)
        V = m172.cond_basis(Fa)
        Fk, Ftek = Fa @ V, Fb @ V
        ev, C, mu, sd = s99.conserved(Fk)
        rat = np.array([s99.heldout(Ftek, C[:, k], mu, sd) for k in range(C.shape[1])])
        o = np.argsort(rat)
        ntake = min(rank_red + 3, C.shape[1])
        cons = np.stack([(((Ftek - mu) / sd) @ C[:, k]).mean(1) for k in o[:ntake]], 1)
        kres = m172.in_span(cons, yK)
        kfres = m172.in_span(cons, ykf)
        n_cons = int((rat <= 1e-9).sum())
        finds = bool(kres < 1e-3 and kres < kfres / 10)
        # rank fallback must be reported, never silent (failure mode 3: a threshold hiding in a fallback branch)
        Zr = (R - R.mean(0)) / (R.std(0) + 1e-300)
        svr = np.linalg.svd(Zr, compute_uv=False)
        fellback = not (len(svr) > 1 and np.diff(np.log10(np.maximum(svr, svr[0] * 1e-300))).min() < -3.0)
        comparable = k_repr < 1e-12
        print(f"{label:16s} {len(Ttr):4d} {rank_red:9d} {dK:10.1e} {r2:11.4f} "
              f"{n_cons:7d} {kres:10.2e} {kfres:10.2e} {str(finds):>8}   "
              f"K_repr={k_repr:.1e}{'' if comparable else '  <-- REFUSED: representability degraded'}"
              f"{'  [rank: no spectral gap, full count]' if fellback else ''}")
        out["rows"].append({"restriction": label, "n_traj": len(Ttr), "reducible_rank": rank_red,
                            "K_drift": dK, "K_irreducible_r2": r2, "n_conserved_below_1e-9": n_cons,
                            "K_residual": kres, "control_residual": kfres, "finds_K": finds,
                            "K_representability": k_repr, "comparable": comparable,
                            "rank_fellback_to_full_count": bool(fellback),
                            "target_survives": bool(dK < 1e-10 and r2 < 0.99)})
    ok = [r for r in out["rows"] if r.get("finds_K") and r.get("comparable")]
    refused = [r for r in out["rows"] if "comparable" in r and not r["comparable"]]
    bad = [r for r in out["rows"] if "finds_K" in r and not r["finds_K"]]
    out["W0_target_survives_all"] = bool(all(r.get("target_survives") for r in out["rows"] if "finds_K" in r))
    out["W3_wall"] = ({"largest_rank_found": max(r["reducible_rank"] for r in ok)} if ok else
                      {"largest_rank_found": None})
    out["n_refused_incomparable"] = len(refused)
    out["verdict"] = (
        "§172'S NEGATIVE DOES NOT TRANSFER TO A TWO-KILLING-VECTOR SPACETIME. At the p_t=0 restriction -- "
        "reducible list {}, K still represented to {:.0e} so the arms are comparable -- the readout ISOLATES "
        "the rank-4 Killing tensor: residual {:.2e} against a non-conserved control at {:.2e}, five orders of "
        "separation. **REFUTED BY §174 -- DO NOT READ THE NEXT CLAUSE AS STANDING.** We concluded from this that, "
        "bumped Kerr having two Killing vectors, §168's degree-4 rungs deserved a RERUN rather than a refusal. "
        "§174 ran that rerun and its ON-SUBSTRATE control failed: withholding Carter from the reducible list on "
        "bumped Kerr at eps=0 leaves it invisible (separation 1.277 vs 1.077), so the readout cannot see a "
        "standout there even when one is certainly present. Validation by REGIME MATCH -- same Killing-vector "
        "count, comparable reducible list -- DOES NOT TRANSFER between substrates. What this script establishes "
        "is only that the readout works at two Killing vectors ON THE CG SUBSTRATE. SCOPE, and it is not the "
        "tidy story: the knob is CONFOUNDED -- pinning momenta shrinks the "
        "algebra but also constrains the velocities, and at p_t=p_w=0 that degrades K's representability by six "
        "orders (1.3e-09 vs ~3e-15), so that row is REFUSED as incomparable rather than read as 'smaller "
        "algebra also fails'. Reducible-algebra SIZE is therefore NOT cleanly isolated as the controlling "
        "variable; what is established is that the failure is not universal."
        .format(max(r["reducible_rank"] for r in ok), max(r["K_representability"] for r in ok),
                min(r["K_residual"] for r in ok), max(r["control_residual"] for r in ok)) if ok else
        "THE NEGATIVE IS ROBUST. The readout fails to isolate a KNOWN rank-4 Killing tensor at every reducible-"
        "algebra size tested, down to a single Killing vector. Degree-4 numerical nulls on a spacetime stay "
        "REFUSED regardless of how few symmetries the metric has, and §168's refusals stand as recorded.")
    print("\n" + out["verdict"])
    (RESULTS / "173_reducible_algebra_wall.json").write_text(json.dumps(out, indent=1))

    rows = [r for r in out["rows"] if "reducible_rank" in r]
    if rows:
        fig, ax = plt.subplots(figsize=(8, 5))
        ax.semilogy([r["reducible_rank"] for r in rows], [r["K_residual"] for r in rows], "o-", label="K residual")
        ax.semilogy([r["reducible_rank"] for r in rows], [r["control_residual"] for r in rows], "s--",
                    label="non-conserved control")
        ax.axhline(1e-3, color="crimson", ls=":", label="finds-K threshold")
        ax.set_xlabel("measured reducible-algebra rank")
        ax.set_ylabel("residual in the conserved span")
        ax.legend(fontsize=8)
        ax.set_title("Where does the degree-4 readout break?\nsame substrate, same target, shrinking reducible algebra")
        fig.tight_layout()
        fig.savefig(RESULTS / "173_reducible_algebra_wall.png", dpi=140)
    print("saved results/173_reducible_algebra_wall.json + .png")


if __name__ == "__main__":
    main()
